FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    cmake make g++ pkgconf curl zip unzip tar git \
    && rm -rf /var/lib/apt/lists/*

# Clone and bootstrap vcpkg
RUN git clone https://github.com/microsoft/vcpkg.git /vcpkg && \
    cd /vcpkg && ./bootstrap-vcpkg.sh

ENV VCPKG_ROOT=/vcpkg

WORKDIR /workspace
